[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"] # EX. `import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";`
# remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
